// Cubik Template version 1.0
// Java generated by Cubik 0.96
// Be sure to check the code and adapt it to your need
// BDcraft.net


package com.blamejared.fluxedcrystals.client.model.pylon;

import net.minecraft.client.model.*;
import net.minecraft.entity.Entity;

public class ModelPylonCube extends ModelBase {
	
	ModelRenderer Elem4;//Cube
	
	public ModelPylonCube() {
		textureWidth = 64;
		textureHeight = 32;
		
		//Cube
		Elem4 = new ModelRenderer(this, 0, 0);
		Elem4.addBox(0F, 0F, 0F, 4, 4, 4);
		Elem4.setRotationPoint(-2F, 14F, -2F);
		Elem4.setTextureSize(64, 32);
		setRotation(Elem4, -0F, -0F, -0F);
		//Elem4.rotateAngleX = -0F;
		//Elem4.rotateAngleY = -0F;
		//Elem4.rotateAngleZ = -0F;
	}
	
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Elem4.render(f5);//Cube
	}
	
	public void render(float f5) {
		render(null, 0, 0, 0, 0, 0, f5);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
	
}
